services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${WEB_CONTAINER_NAME:-toothy-planner-web}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BASE_URL: ${BASE_URL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${WEB_PORT:-8014}:80'
